### ISSUE TITLE
Get 'Date' into the Create and Update forms

### ISSUE THREAD

**Issue by drewmccarron** [We-Work-On-Master/hangout-client#17]
Replace the current text-fields for "Date" on the Create and Update forms with a drop-down calendar.

**Comment by bhmdev** [comment]
Finished the date - only issue is that is shows like this: 
<img width="340" alt="Screen Shot 2020-03-13 at 11 01 38 AM" src="https://user-images.githubusercontent.com/58837914/76632708-04a99880-651a-11ea-9306-97b08f37e7b8.png">
